CBLClient/Apps/CBLTestServer-Android/app/build.gradle
CBLClient/Apps/CBLTestServer-Android/build.gradle
CBLClient/Apps/CBLTestServer-Android/gradle/wrapper/gradle-wrapper.properties

Update the tool chain and fix the logging in the ZipUtil

Update tool chain

---

CBLClient/Apps/CBLTestServer-iOS/Cartfile
CBLClient/Apps/CBLTestServer-iOS/build_ios_testserver_app.sh

Currently Testserver app build always shows success though there are some failures, if we know the build status it will be easy to narrow down the app deployment issue faster
Recently we spent couple days to debug the app deployment issues

Change will mark the build to fail

---

CBLClient/Apps/CBLTestServer-Android/app/build.gradle
CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/DatabaseRequestHandler.java
CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/LoggingRequestHandler.java
CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/ReplicatorRequestHandler.java
CBLClient/Apps/JavaRequestListener/src/main/java/com/couchbase/mobiletestkit/javalistener/Server.java

android build fixes for cblite 3.0

Fix/build cblite android 3.0

---

CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/DatabaseRequestHandler.swift

App side changes for _id and _rev compatible change.
http://uberjenkins.sc.couchbase.com:8080/job/CBLITE_iOS-Listener-TestServer-Functional-XATTRS-tests/73/
http://mobile.jenkins.couchbase.com/view/CBL%202.x/job/couchbase-lite-ios-testapp/768/

Fix ios _id changes

---

CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/ListenerAuthenticatorRequestHandler.swift
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/PeerToPeerRequestHandler.swift
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/PredictiveQueriesRequestHandler.swift
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/ReplicatorTcpClientConnection.swift
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/ReplicatorTcpConnection.swift
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/ReplicatorTcpListener.swift
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/ReplicatorTcpServerConnection.swift
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/Server.swift
CBLClient/Apps/CBLTestServer-iOS/build_ios_testserver_app.sh

http://mobile.jenkins.couchbase.com/view/CBL%202.x/job/couchbase-lite-ios-testapp/786/  CE Build
http://mobile.jenkins.couchbase.com/view/CBL%202.x/job/couchbase-lite-ios-testapp/788/ EE Build

Adding CE support to Test Server APP

---

CBLClient/Apps/CBLTestServer-Android/app/build.gradle
CBLClient/Apps/CBLTestServer-Java-Desktop/build.gradle
CBLClient/Apps/CBLTestServer-Java-WS/build.gradle

update maven url with the newly setup dns

---

CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/ListenerAuthenticatorRequestHandler.swift
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/PeerToPeerRequestHandler.swift
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/PredictiveQueriesRequestHandler.swift
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/Server.swift

All predictive query tests are failing due to the missing handler, with this app changes it will fix 
App builds
http://mobile.jenkins.couchbase.com/view/CBL 2.x/job/couchbase-lite-ios-testapp/804
http://mobile.jenkins.couchbase.com/view/CBL%202.x/job/couchbase-lite-ios-testapp/801/
tests:
http://uberjenkins.sc.couchbase.com:8080/job/CBLITE_iOS-Listener-TestServer-Functional-XATTRS-tests/85/

Test fixes - predictive queries

---

CBLClient/Apps/CBLTestServer-iOS/build_ios_testserver_app.sh

simulator builds for xc framework
http://mobile.jenkins.couchbase.com/view/CBL%202.x/job/couchbase-lite-ios-testapp/918/
http://uberjenkins.sc.couchbase.com:8080/job/CBLITE_IOS_Functional-TestServer-BackgroundAppTests/138/

Copying the ios simulator builds

---

CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/DictionaryRequestHandler.java

https://issues.couchbase.com/browse/CM-754

fix android/java build

---

CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/DatabaseRequestHandler.java

a minor change to fix the build due to cblite java/android api changes

add a fix due to java-android api changes

---

CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/ReplicatorRequestHandler.swift

http://mobile.jenkins.couchbase.com/view/CBL%202.x/job/couchbase-lite-ios-testapp/1020/

Fix/resetcheckpoint api change for IOS

---

CBLClient/Apps/CBLTestServer-Dotnet/TestServer/ReplicationMethods.cs

We updated the Android and ios in different PRs

reset checkpoint

---

CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/DatabaseConfigurationRequestHandler.swift
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/PeerToPeerRequestHandler.swift
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/ReplicatorConfigurationRequestHandler.swift

http://mobile.jenkins.couchbase.com/view/CBL 2.x/job/couchbase-lite-ios-testapp/1026/

fixing enhanced config changes for ios

---

CBLClient/Apps/CBLTestServer-Android/app/build.gradle
CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/PeerToPeerRequestHandler.java
CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/ReplicatorConfigurationRequestHandler.java
CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/ReplicatorRequestHandler.java

1. heartbeat data type changed from long => int
2. ReplicatorStatus class is introduced to replace Replicator.Status enum

fix testserver app build due to CBLite api changes

---

CBLClient/Apps/CBLTestServer-Dotnet/TestServer.UWP/MainPage.xaml.cs
CBLClient/Apps/CBLTestServer-Dotnet/TestServer/ReplicatorConfigurationMethods.cs

http://mobile.jenkins.couchbase.com/view/CBL%202.x/job/couchbase-lite-net-testapp/328/

uwp loglevel changes

---

CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/PeerToPeerRequestHandler.swift
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/ReplicatorConfigurationRequestHandler.swift

As retry api names and logic changes this sprint , IOS test app build is failing.
This change will fix it.
http://mobile.jenkins.couchbase.com/view/CBL%202.x/job/couchbase-lite-ios-testapp/

new retry changes for ios build 162

---

CBLClient/Apps/CBLTestServer-Dotnet/TestServer/DatabaseMethods.cs
CBLClient/Apps/CBLTestServer-Dotnet/TestServer/P2PMethods.cs
CBLClient/Apps/CBLTestServer-Dotnet/TestServer/ReplicatorConfigurationMethods.cs

Latest .net build required changes
revised retries api and compact api for net.
http://mobile.jenkins.couchbase.com/view/CBL%202.x/job/couchbase-lite-net-testapp/331/

Updating revised retries api and compact api for net.

---

CBLClient/Apps/CBLTestServer-Android/app/build.gradle

build environment has upgraded ndk version. fix it in build.gradle to ensure the android build works

upgrade ndk version and target sdk version

---

CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/CollatorRequestHandler.java
CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/QueryRequestHandler.java

fix android & java build due to CBLite API changes.

fix java/android build due to CBLite changes

---

CBLClient/Apps/CBLTestServer-Android/app/src/main/java/com/couchbase/CouchbaseLiteServ/CouchbaseLiteServ.java
CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/ReplicatorConfigurationRequestHandler.java
CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/ReplicatorRequestHandler.java

update calls to use the latest CBLite android APIs

update document flags usage to fix android build

---

CBLClient/Apps/CBLTestServer-Android/app/build.gradle

update android package since dev renamed it

update android package names

---

CBLClient/Apps/CBLTestServer-Dotnet/TestServer.NetCore/TestServer.NetCore.csproj

.net app is missing the 2.8 upgrade config. But it has the prebuild dbs.

2.8 upgrade change

---

CBLClient/Apps/CBLTestServer-Dotnet/TestServer/BlobMethods.cs

this fixes .net runtime file directory location.

fix a blob file location issue for windows platform

---

CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/PeerToPeerRequestHandler.java
CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/ReplicatorConfigurationRequestHandler.java

update the java/android shared request handler code to use the new ReplicatorType class, it was property of ReplicationConfiguration class. tested build 3.1.0-121 and running regression current.

Fix/android java 3.1 build

---

CBLClient/Apps/CBLTestServer-C/ios/TestServer/TestServer.xcodeproj/project.pbxproj
CBLClient/Apps/CBLTestServer-C/src/CollectionMethods.cpp
CBLClient/Apps/CBLTestServer-C/src/CollectionMethods.hpp
CBLClient/Apps/CBLTestServer-C/src/ReplicatorConfigurationMethods.cpp
CBLClient/Apps/CBLTestServer-C/src/Router.cpp
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS.xcodeproj/project.pbxproj
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/CollectionRequestHandler.swift
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/ReplicatorConfigurationRequestHandler.swift
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/ScopeRequestHandler.swift
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/Server.swift

these changes are based on feedback from @jayahariv

ios_framework

---

CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/CollectionRequestHandler.swift

added a new method to iOS framework required for a test_case.

test_same_collection_in_different_scope fix

---

CBLClient/Apps/CBLTestServer-C/src/ReplicatorConfigurationMethods.cpp
CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Server/CollectionRequestHandler.swift

The Pr consist of fix of invalid memory address.

CBL_C Jenkins Scopes and Collections Replication Fix

---

CBLClient/Apps/CBLTestServer-Dotnet/NuGet.config
CBLClient/Apps/CBLTestServer-Dotnet/TestServer.Android/Properties/AndroidManifest.xml
CBLClient/Apps/CBLTestServer-Dotnet/TestServer.Android/Resources/Resource.Designer.cs
CBLClient/Apps/CBLTestServer-Dotnet/TestServer.Android/TestServer.Android.csproj
CBLClient/Apps/CBLTestServer-Dotnet/TestServer.Android/build.ps1
CBLClient/Apps/CBLTestServer-Dotnet/TestServer.NetCore/TestServer.NetCore.csproj
CBLClient/Apps/CBLTestServer-Dotnet/TestServer.NetCore/build.ps1
CBLClient/Apps/CBLTestServer-Dotnet/TestServer.UWP/TestServer.UWP.csproj
CBLClient/Apps/CBLTestServer-Dotnet/TestServer.UWP/build.ps1
CBLClient/Apps/CBLTestServer-Dotnet/TestServer.UWP/run.ps1
CBLClient/Apps/CBLTestServer-Dotnet/TestServer.iOS/TestServer.iOS.csproj
CBLClient/Apps/CBLTestServer-Dotnet/TestServer/TestServer.csproj

Using VS 2022 , Android 10, etc, and fixing build errors that happen because of it.

Update .NET test app 

---

CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS/Info.plist

Reverts couchbaselabs/mobile-testapps#126

Revert "Disable NSAllowsArbitraryLoads"

---

CBLClient/Apps/CBLTestServer-Android/app/build.gradle
CBLClient/Apps/CBLTestServer-Android/app/src/main/AndroidManifest.xml
CBLClient/Apps/CBLTestServer-Android/app/src/main/java/com/couchbase/CouchbaseLiteServ/MainActivity.java
CBLClient/Apps/CBLTestServer-Android/build.gradle
CBLClient/Apps/CBLTestServer-Android/gradle.properties
CBLClient/Apps/CBLTestServer-Android/gradle/wrapper/gradle-wrapper.properties
CBLClient/Apps/CBLTestServer-Android/settings.gradle
CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/VectorSearchRequestHandler.java

This thing compiles now.  There are some issues here; the first couple are pretty serious:
- it needs to be upgraded to use androidx packages.  I'm not sure it will even run, as is.
- VectorSearchRequestHandler.handleRequest seems to want to return an Object.  Collection.createIndex() is void.  I've made it compile but it surely isn't right.
- VectorIndexConfiguration.DistanceMetric.EUCLIDIAN is a misspelling on my part.  It will be fixed in the next versions to be VectorIndexConfiguration.DistanceMetric.EUCLIDEAN

Gradle runs and the project compiles

---

CBLClient/Apps/CBLTestServer-C/build_scripts/build_cross.py
CBLClient/Apps/CBLTestServer-C/src/CollectionMethods.cpp
CBLClient/Apps/CBLTestServer-C/src/Defines.h
CBLClient/Apps/CBLTestServer-C/src/TestServer.cpp
CBLClient/Apps/CBLTestServer-C/src/VectorSearchMethods.cpp

Vector search test app handler for C. Tested with the vector search tests and other tests, to see that nothing is broken.

Vector search c

---

CBLClient/Apps/CBLTestServer-C/src/VectorSearchMethods.cpp

Fix a build problem due to 2 changes in vector vectors:
- Change CBL_SetExtensionPath to CBL_EnableVectorSearch
- Change the predict function to return MutableDict

Fix a C test app build breakage

---

CBLClient/Apps/CBLTestServer-C/src/VectorSearchMethods.cpp

CBL_EnableVectorSearch new receives and error object

Fix a build problem

---

CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/CollectionRequestHandler.java
CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/VectorSearchRequestHandler.java

Add lazy vector functionality to Android/Java

---

CBLClient/Apps/CBLTestServer-Android/app/build.gradle
CBLClient/Apps/CBLTestServer-Android/build.gradle

Update the Android API version

---

CBLClient/Apps/CBLTestServer-iOS/CBLTestServer-iOS.xcodeproj/project.pbxproj

Update the deployment target.
Tested in Jenkins by building and running sanity tests.

Update the iOS deployment target

---

CBLClient/Apps/CBLTestServer-C/build.gradle

Tested in Jenkins and the manual sanity test of running the app on the phone and communicating with it.

Update c android sdk

---

CBLClient/Apps/CBLTestServer-Java-Desktop/build.gradle
CBLClient/Apps/CBLTestServer-Java-Desktop/gradle/wrapper/gradle-wrapper.properties

Tested by building and then running sample Java tests

Upgrade the Gradle build

---

CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/RequestHandler/QueryRequestHandler.java
CBLClient/Apps/JavaRequestHandlers/src/main/java/com/couchbase/mobiletestkit/javacommon/ValueSerializer.java

Tested by building and running selected suites

Fix build warnings

---

CBLClient/Apps/CBLTestServer-Java-Desktop/src/main/java/com/couchbase/mobiletestkit/javatestserver/TestServerMain.java

Enable VS for Java

---

CBLClient/Apps/CBLTestServer-Java-WS/build.gradle
CBLClient/Apps/CBLTestServer-Java-WS/gradle/wrapper/gradle-wrapper.properties

Tested by building the Java WS test app

Fix the Java ws build
